### ISSUE TITLE
no pg_hba.conf entry for host ..., no encryption

### ISSUE THREAD

**Issue by jac0x** [joshstevens19/rindexer#116]
```
21 November - 02:24:52.913122 ERROR Error connecting to database: db error: FATAL: no pg_hba.conf entry for host "xxx", user "postgres", database "postgres", no encryption
Error: "The DATABASE_URL mapped is not running please make sure it is correct"
```

This error occurs when connecting to AWS postgres db.

Seems this is related to https://stackoverflow.com/questions/76899023/rds-while-connection-error-no-pg-hba-conf-entry-for-host/77787495#77787495

Does it mean for now, it doesn't use SSL connection?

**Comment by joshstevens19** [comment]
yeah try psql aka the full DATABASE_URL see if it connects aka 

`psql "postgresql://username:password@hostname:5432/database_name"` 

with AWS normally error above is to do with some setup on AWS side:

The most common causes for this error with AWS RDS are:

- Security group not allowing your IP

Make sure the RDS security group allows inbound access on port 5432 from your IP address
You can add your IP to the security group: Type: PostgreSQL, Protocol: TCP, Port: 5432, Source: Your-IP/32

- Missing SSL in the connection string 

make sure if you are using SSL you put in ?sslmode=require in connection string aka:

`psql "postgresql://postgres:password@your-rds-endpoint.region.rds.amazonaws.com:5432/postgres?sslmode=require"`

- Incorrect endpoint/credentials

make sure your connection string is fully correct - using psql is the best approach as you can verify by the same DATABASE_URL your using with rindexer.

Closing for now if you still have issues i will reopen thanks
