### ISSUE TITLE
Create railway deployment documentation

### ISSUE THREAD

**Issue by joshstevens19** [joshstevens19/rindexer#15]
We do not have docs to show the user how to deploy an rindexer so we should create some

**Comment by o-az** [comment]
wip here https://github.com/o-az/rindexer-railway

once done there will be a button to deploy. One click then fill out env variables in railway then up and running. Feel free to assign to me

**Comment by o-az** [comment]
[![Deploy on Railway](https://railway.app/button.svg)](https://railway.app/template/Rqrlcf?referralCode=eD4laT)

https://github.com/o-az/rindexer-railway/tree/main

need to update docs to add guide now then should be sorted for railway

**Comment by o-az** [comment]
Can close now?

**Comment by joshstevens19** [comment]
This is now complete thanks to @o-az 

https://rindexer.xyz/docs/deploying/railway
