### ISSUE TITLE
Can't get panic error message

### ISSUE THREAD

**Issue by FreezyEx** [joshstevens19/rindexer#45]
It seems there is a wrong type inside my abis looking to  https://github.com/joshstevens19/rindexer/blob/56ad08e1158033e54e9a447d8cb7b97c29ef34bd/core/src/database/postgres/generate.rs#L211

but it does't print the wrong `baseType`

Error:

`=== Start Of Custom rindexer unhandled panic hook - please supply this information on the github issue if it happens ===
Panic occurred in file '/home/runner/work/rindexer/rindexer/core/src/database/postgres/generate.rs' at line 211
Panic occurred but can't get the panic message...
Backtrace [{ fn: "rindexer_cli::set_panic_hook::{{closure}}::{{closure}}" }, { fn: "std::panicking::rust_panic_with_hook" }, { fn: "std::panicking::begin_panic_handler::{{closure}}" }, { fn: "std::sys::backtrace::__rust_end_short_backtrace" }, { fn: "rust_begin_unwind" }, { fn: "core::panicking::panic_fmt" }, { fn: "<core::iter::adapters::flatten::FlattenCompat<I,U> as core::iter::traits::iterator::Iterator>::next" }, { fn: "<alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter" }, { fn: "rindexer::database::postgres::setup::setup_postgres::{{closure}}" }, { fn: "rindexer::start::start_rindexer_no_code::{{closure}}" }, { fn: "rindexer_cli::commands::start::start::{{closure}}" }, { fn: "rindexer_cli::main::{{closure}}" }, { fn: "rindexer_cli::main" }, { fn: "std::sys::backtrace::__rust_begin_short_backtrace" }, { fn: "std::rt::lang_start::{{closure}}" }, { fn: "main" }, { fn: "__libc_start_main" }, { fn: "_start" }]
=== End Of Custom rindexer unhandled panic hook - please supply this information on the github issue if it happens ===`

-------------
### UPDATE
The issue is that some solidity types are missing inside `core/src/database/postgres/generate.rs`. For this reason it fails to parse the ABI. 
To reproduce just try using Uniswap V3 Pair abi.

**Comment by joshstevens19** [comment]
ah yes i will fix that as solidity does support integer types with any size that is a multiple of 8 from 8 to 256 bits - fixing shortly

**Comment by joshstevens19** [comment]
fixed - https://github.com/joshstevens19/rindexer/commit/74e2944bf4d613b20b1087f667f670298b114a5d will deploy shortly

**Comment by joshstevens19** [comment]
fixed and deployed
