### ISSUE TITLE
Network chainid is greater than u32 causes panic

### ISSUE THREAD

**Issue by plotchy** [joshstevens19/rindexer#53]
Unfortunately chainids have grown past what is normally expected 😅

```
❯ rindexer codegen typings
Could not read the rindexer.yaml file: Could not parse manifest: networks[0].chain_id: invalid value: integer `5264468217`, expected u32 at line 6 column 13
```

**Comment by joshstevens19** [comment]
lol good find let me fix this tomorrow thanks for raising

**Comment by joshstevens19** [comment]
fixed - https://github.com/joshstevens19/rindexer/commit/b19ac417b7de93846b139d67afdd63ab4f4b7fc6 will deploy today

**Comment by joshstevens19** [comment]
https://github.com/joshstevens19/rindexer/pull/58 - rindexerup will get the latest one
