### ISSUE TITLE
Unable to install rindexer on Mac (Darwin x86_64)

### ISSUE THREAD

**Issue by AdeThorMiwa** [joshstevens19/rindexer#80]
Running the install script at `curl -L https://rindexer.xyz/install.sh | bash` is failing with a 404 not found at line `curl -sSf -L "$BIN_URL" -o "$RINDEXER_DIR/rindexer.${EXT}"`

**Comment by joshstevens19** [comment]
Can you show me the full error? What Mac have you got and the software version?

**Comment by AdeThorMiwa** [comment]
![Screenshot 2024-08-11 at 2 36 16 PM](https://github.com/user-attachments/assets/dbaa91b5-659c-4d90-b6fe-3586c3f77997)

On a Macbook 2020 Ventura Intel x86_64

**Comment by joshstevens19** [comment]
Ok can take a look when back later

**Comment by joshstevens19** [comment]
hey pushed a fix please try again @AdeThorMiwa will mark as close but let me know if still issues and i will look further

**Comment by AdeThorMiwa** [comment]
Hi @joshstevens19 , its still returning the same 404 error. I think the problem might be that the release does not include/build a binary for `darwin-x86_64` which is what the curl command is trying to download in the install.sh file. I tried on a friends macbook `darwin-arm64` and it works

**Comment by joshstevens19** [comment]
Yeah I thought I fixed it here to reroute correctly https://github.com/joshstevens19/rindexer/commit/dd0d960b5b0899224c44266cac4371f49d69aedc > does your error say the same thing or a different URL showed on downloading binary archive?

**Comment by joshstevens19** [comment]
Can you make sure your browsers not caching it or anything?

**Comment by joshstevens19** [comment]
try .sh?donotcacheme=true on the end just want to avoid it being a cache thing as the install script should reroute it now

**Comment by AdeThorMiwa** [comment]
Yeah, works now! Thanks very much

**Comment by joshstevens19** [comment]
Great! 💪
