### ISSUE TITLE
Docker Image is an old version of rindexer

### ISSUE THREAD

**Issue by gllm-dev** [joshstevens19/rindexer#85]
![Screenshot 2024-08-13 at 15 05 44](https://github.com/user-attachments/assets/e0a9f77b-e8c7-4268-b615-a7aa2a97cbc7)

Running ghcr.io/joshstevens19/rindexer:latest docker is using 0.3.1 rindexer version

**Comment by joshstevens19** [comment]
yeah this seems to of broke in last build with stream @crebsy is going to take a look at it

**Comment by joshstevens19** [comment]
this is now released with the new docker version @gllm-dev

**Comment by gllm-dev** [comment]
Ty!
