### ISSUE TITLE
ERROR Failed to start GraphQL server: GraphQLServerStartupError("rindexer-graphql executable not found")

### ISSUE THREAD

**Issue by cardene777** [joshstevens19/rindexer#89]
When deploying to railway, graphql would not start up forever after a successful deployment.
This problem was resolved in Version 0.6.1 with a fix for an event name conflict.
https://github.com/joshstevens19/rindexer/pull/86

When I ran ‘railway up’ in railway again, I got an `ERROR Failed to start GraphQL server: GraphQLServerStartupError(’rindexer-graphql executable not found")` Error.
*We keep a log of the whole process below

https://github.com/cardene777/Xenea-Indexer-Template/blob/develop/logs/xenea-indexer/2024-08-17-railway.log

The deployment itself is successful, so accessing the site shows ‘ Application failed to respond’.
https://xenea-indexer-production.up.railway.app/

How can I access the site successfully?
By the way, we are proceeding as per the documentation and have registered the following environment variables in the ‘Variables’ section of the service.

```
DATABASE_URL -> ${{Postgres.DATABASE_URL}}?sslmode=disable
PORT -> 3001
```
https://rindexer.xyz/docs/deploying/railway
In addition, the deployed code is as follows.
https://github.com/cardene777/Xenea-Indexer-Template/tree/develop/rindexer/xenea-indexer

**Comment by crebsy** [comment]
@cardene777 the normal docker image `rindexer` only contains the rindexer binary.

You can use this `rindexer-bundled` image instead which contains graphql as well:
https://github.com/joshstevens19/rindexer/pkgs/container/rindexer-bundled

**Comment by cardene777** [comment]
@crebsy 

Thank you!

```bash
FROM ghcr.io/joshstevens19/rindexer:latest AS rindexer
```

The above could be converted and deployed as follows!

```bash
FROM ghcr.io/joshstevens19/rindexer-bundled:sha-71496999f078a46b7bbffc4363a903ea9a3c3282 AS rindexer
```
