### ISSUE TITLE
`rindexer codegen typings` leaks absolute paths

### ISSUE THREAD

**Issue by roshanr95** [joshstevens19/rindexer#94]
As in the title, the command generates files which contain absolute paths. Are the generated files not supposed to be checked into VCS? If not, happy to make a PR that makes them relative.

**Comment by joshstevens19** [comment]
Hey thanks for this yes it’s a bug feel free to fix it happily accept a PR

**Comment by joshstevens19** [comment]
do you want to take this @roshanr95 if so great - i am away till next week and can fix once back if not

**Comment by roshanr95** [comment]
Yes, I'll take this. I can either sanitize the absolute path before printing to file, or purge absolute paths in the codebase (i.e. `std::env::current_dir`) as much as possible if not entirely. Which option would you prefer?

**Comment by joshstevens19** [comment]
yeah probably can just use `../../../` approach to be honest - awesome thanks good spot as well as would break for people when they deploy it haha

**Comment by roshanr95** [comment]
`Abigen` seems to convert relative paths into absolute paths internally :cry:

**Comment by roshanr95** [comment]
Ah ok, opened a couple of PRs with my existing changes btw. At a conference atm, so will take a week to get back to this in case it's still open.

**Comment by joshstevens19** [comment]
hey not had time to look at these but I've spotted a few other places 
![image](https://github.com/user-attachments/assets/ba024bff-0fa7-4db6-9253-161efe81eb41)
aka in the handler itself does your fix any of that I'm not working on a project which is going to use rindexer so we can get this all fixed

**Comment by joshstevens19** [comment]
should now not be valid as we bring ABI in the typings itself instead of looking at the file this just means any changes to ABI we would regen the types but that feels better anyway still one lives on in csv stuff but il fix that also
