### ISSUE TITLE
flexibility to have `bulk_update`, `bulk_delete` and `bulk_query` functionalities inside postgres `client.rs`

### ISSUE THREAD

**Issue by souvikmishra** [joshstevens19/rindexer#95]
Hi @joshstevens19 as I am actively using this project, having the ability to `bulk_insert` stuff is great. I was hoping we could add in more functionalities like this such as in the title. If this falls within the scope of the project I would be happy to contribute. Cheers 🍻

**Comment by joshstevens19** [comment]
did you mean to close this @souvikmishra

**Comment by souvikmishra** [comment]
Wasn't really sure if it fell under the scope of this project 😕 and didn't want to bug you unnecessarily 😅.
